name: 'Docker Build (Ubuntu)'

on: [push]

#on: 
#  push:
#    paths:
#      - 'containers/Dockerfile'

env:
  TEST_TAG: ipta-env:test

jobs:
  build-docker-image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      max-parallel: 5
    steps:
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Test Docker Image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:containers"
          push: false
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test Docker
        run: |
          docker run --rm ${{ env.TEST_TAG }}
