name: 'Conda Env Verified (Ubuntu & MacOS)'

on:
  pull_request:
    paths:
      - '**-env.yml'
      - '.github/workflows/**'

jobs:
  build-conda-env:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: false
    - name: Install Conda Environment on MacOS
      if: matrix.os == 'macos-latest'
      run: |
        micromamba env create --platform osx-64 --file anaconda-env.yml
    - name: Install Conda Environment on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        micromamba env create --file anaconda-env.yml
