name: 'Conda Env Verified (Ubuntu & MacOS)'

on:
  pull_request:
    paths:
      - '**-env.yml'

jobs:
  build-conda-env:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Add Conda to System Path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Add libMamba Solver to Conda Base Environment
      run: |
        conda update -n base conda
        conda install -n base conda-libmamba-solver
        conda config --set solver libmamba
    - name: Install Conda Environment
      run: |
        conda env create --file anaconda-env.yml
