name: 'Conda Env Verified (Ubuntu & MacOS)'

on:
  pull_request:
    paths:
      - '**-env.yml'

jobs:
  build-conda-env:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: false
    - name: Install Conda Environment
      run: |
        conda env create --file anaconda-env.yml
