name: 'Apptainer Build (Ubuntu)'

#on: [push]

on: 
  push:
    paths:
      - 'containers/Singularity'

jobs:
  build-apptainer-image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      max-parallel: 5
    steps:
      - uses: actions/checkout@v2
      - uses: eWaterCycle/setup-apptainer@v2.0.0
        with:
          apptainer-version: 1.1.3
      - name: Run an apptainer container
        run: |
          apptainer build image-build containers/Singularity.def 
