name: 'Docker Build (Ubuntu)'

on: [push]

#on: 
#  push:
#    paths:
#      - 'containers/Dockerfile'

env:
  TEST_TAG: ipta-env.docker:test

jobs:
  build-apptainer-image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      max-parallel: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Test Docker Image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:containers"
          push: false
          tags: ${{ env.TEST_TAG }}
      - name: Test Docker
        run: |
          docker run --rm ${{ env.TEST_TAG }}
